# This rule is not used by the project cost-optimizer-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the optimization.stackbalancer.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cost-optimizer-operator
    app.kubernetes.io/managed-by: kustomize
  name: resourceoptimizer-editor-role
rules:
- apiGroups:
  - optimization.stackbalancer.io
  resources:
  - resourceoptimizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimization.stackbalancer.io
  resources:
  - resourceoptimizers/status
  verbs:
  - get
