apiVersion: optimization.stackbalancer.io/v1
kind: ResourceOptimizer
metadata:
  labels:
    app.kubernetes.io/name: cost-optimizer-operator
    app.kubernetes.io/managed-by: kustomize
  name: resourceoptimizer-sample
spec:
  # TODO(user): Add fields here
  foo: bar
